apiVersion: apps/v1
kind: Deployment
metadata:
  name: owasp-juice
spec:
  selector:
    matchLabels:
      app: juice
  replicas: 1
  template:
    metadata:
      labels:
        app: juice
    spec:
      containers:
      - name: juice
        image: bkimminich/juice-shop
        ports:
        - containerPort: 3000