Create a Pod with the service account
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
spec:
  containers:
  - image: nginx:latest
    name: nginxpod
  serviceAccountName: mikeuser
  automountServiceAccountToken: false