apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2immediate
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate